package de.tr0llhoehle.disease;

public enum UIState {
    INIT, MAP, ZOMBIE, ZOMBIE_READYING, ZOMBIE_HIT, ZOMBIE_DEFENDED, ZOMBIE_HIT_BY_PLAYER, ZOMBIE_DEFEATED, KILLED,
    PERSON, PERSON_YOU_RAN_AWAY, PERSON_THEY_RAN_AWAY, PERSON_WAITING, PERSON_BOTH_ATTACK, PERSON_BOTH_BEFRIEND,
    PERSON_WON_FIGHT, PERSON_LOST_FIGHT, PERSON_ROBBING_SUCCESS, PERSON_GOT_ROBBED,
    PICKED_UP_FOOD, PICKED_UP_DRINK
}
